SELECT TOP (1000) [id_User]
      ,[id_inspector]
      ,[VigenciaLicencia]
      ,[Usuario]
      ,[Password]
      ,[Cargo]
      ,[Correo]
      ,[Estado]
  FROM [upt_TrabajoInspectores].[dbo].[tbUsuariosPrograma]
